#*******************************************************************************
#                                                                              #
#          .oOOOo.   o      o       .oOOOo.         o                 o        #
#         .O     o. O      O        o     o        O                 O         #
#         O       o o      o        O.             o                 o         #
#         o       O O      o         `OOoo.        O                 O         #
#         O       o o  .oOoO              `O .oOo  OoOo. .oOo. .oOo. o         #
#         o       O O  o   O               o O     o   o O   o O   o O         #
#         `o     O' o  O   o        O.    .O o     o   O o   O o   O o         #
#          `OoooO'  Oo `OoO'o        `oooO'  `OoO' O   o `OoO' `OoO' Oo        #
#                                                                              #
#  Author : lee-shun                                                           #
#                                                                              #
#  Email  : 2015097272@qq.com                                                  #
#                                                                              #
#*******************************************************************************

[[plugins]]
repo = 'niklaas/lightline-gitdiff'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['lightline-gitdiff', 'vim-fugitive']
on_event = ['BufReadPre']
hook_add = '''
source $CONF_PATH/plug_conf/lightline_conf.vim
'''

[[plugins]]
repo = 'luochen1990/rainbow'
on_event = ['BufReadPost']
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_event = ['BufReadPre']
hook_add = '''
source $CONF_PATH/plug_conf/indentLine_conf.vim
'''

[[plugins]]
repo = 'RRethy/vim-illuminate'
on_event = ['BufReadPost']

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_event = ['BufReadPost']
hook_add = '''
let g:floaterm_keymap_toggle = '<F12>'
nnoremap <leader>ra :FloatermNew --height=0.6 --width=0.8 --wintype=float ranger<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['fern-git-status.vim','fern-renderer-nerdfont.vim']
on_event = ['BufReadPost']
hook_add = '''
source $CONF_PATH/plug_conf/fern_conf.vim
'''

[[plugins]]
repo = 'airblade/vim-rooter'
on_event = ['BufReadPost']
hook_add = '''
let g:rooter_change_directory_for_non_project_files = 'current'
let g:rooter_patterns = ['.vim_root', 'compile_commands.json','.clang-format','.git','=code','package.xml']
'''

[[plugins]]
repo = 'Yggdroot/LeaderF'
on_map  = {n='<leader>f'}
hook_add = '''
source $CONF_PATH/plug_conf/leaderF_conf.vim
'''

[[plugins]]
repo = 'chrisbra/Colorizer'
on_event = ['BufReadPost']
on_cmd = ['ColorToggle']

[[plugins]]
repo = 'sakshamgupta05/vim-todo-highlight'
on_event = ['BufReadPost']
hook_add  = '''
let g:todo_highlight_config = {
            \   'STEP': {
            \     'gui_fg_color': '#ffffff',
            \     'gui_bg_color': '#27AE60 ',
            \     'cterm_fg_color': 'white',
            \     'cterm_bg_color': 'green' },
            \   'NOTE': {
            \     'gui_fg_color': '#ffffff',
            \     'gui_bg_color': '#ffbd2a',
            \     'cterm_fg_color': 'white',
            \     'cterm_bg_color': '214'
            \   }
            \ }
'''

[[plugins]]
repo = 'junegunn/vim-peekaboo'
on_event = ['BufReadPost']

[[plugins]]
repo = 'tpope/vim-speeddating'
on_event = ['BufReadPost']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = ['BufReadPost']
on_map = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'mg979/vim-visual-multi'
on_map = {n='<C-n>'}

[[plugins]]
repo = '907th/vim-auto-save'
on_event = ['BufReadPost']
hook_add  = '''
source $CONF_PATH/plug_conf/auto_save_conf.vim
'''

[[plugins]]
repo = 'lambdalisue/readablefold.vim'
on_event = ['BufReadPost']

[[plugins]]
repo = 'wellle/targets.vim'
on_event = ['BufReadPost']

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'thinca/vim-textobj-between'
depends = ['vim-textobj-user']
on_event = ['BufReadPost']

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = ['UndoTreeToggle']

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_event = ['BufReadPost']

[[plugins]]
repo = 'skywind3000/asynctasks.vim'
depedns=['asyncrun.vim']
on_event = ['BufReadPost']
