#*******************************************************************************
#                                                                              #
#          .oOOOo.   o      o       .oOOOo.         o                 o        #
#         .O     o. O      O        o     o        O                 O         #
#         O       o o      o        O.             o                 o         #
#         o       O O      o         `OOoo.        O                 O         #
#         O       o o  .oOoO              `O .oOo  OoOo. .oOo. .oOo. o         #
#         o       O O  o   O               o O     o   o O   o O   o O         #
#         `o     O' o  O   o        O.    .O o     o   O o   O o   O o         #
#          `OoooO'  Oo `OoO'o        `oooO'  `OoO' O   o `OoO' `OoO' Oo        #
#                                                                              #
#  Author : lee-shun                                                           #
#                                                                              #
#  Email  : 2015097272@qq.com                                                  #
#                                                                              #
#*******************************************************************************

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
hook_post_update = '''
echom "hello"
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'rhysd/conflict-marker.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mhinz/vim-signify'
