#*******************************************************************************
#                                                                              #
#          .oOOOo.   o      o       .oOOOo.         o                 o        #
#         .O     o. O      O        o     o        O                 O         #
#         O       o o      o        O.             o                 o         #
#         o       O O      o         `OOoo.        O                 O         #
#         O       o o  .oOoO              `O .oOo  OoOo. .oOo. .oOo. o         #
#         o       O O  o   O               o O     o   o O   o O   o O         #
#         `o     O' o  O   o        O.    .O o     o   O o   O o   O o         #
#          `OoooO'  Oo `OoO'o        `oooO'  `OoO' O   o `OoO' `OoO' Oo        #
#                                                                              #
#  Author : lee-shun                                                           #
#                                                                              #
#  Email  : 2015097272@qq.com                                                  #
#                                                                              #
#*******************************************************************************

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# ==
# == UI
# ==

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source $CONF_PATH/plug_conf/lightline_conf.vim
'''

[[plugins]]
repo = 'niklaas/lightline-gitdiff'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source $CONF_PATH/plug_conf/indentLine_conf.vim
'''

[[plugins]]
repo = 'RRethy/vim-illuminate'

[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_add = '''
let g:floaterm_keymap_toggle = '<F12>'
nnoremap <leader>ra :FloatermNew --height=0.6 --width=0.8 --wintype=float ranger<CR>
'''

# ==
# == File navigation
# ==

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['fern-git-status.vim','fern-renderer-nerdfont.vim']
hook_add = '''
source $CONF_PATH/plug_conf/fern_conf.vim
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_change_directory_for_non_project_files = 'current'
let g:rooter_patterns = ['.vim_root', 'compile_commands.json','.clang-format','.git','=code','package.xml']
'''

# ==
# == File Finder
# ==

[[plugins]]
repo = 'Yggdroot/LeaderF'
hook_add = '''
source $CONF_PATH/plug_conf/leaderF_conf.vim
'''

# ==
# == General Highlight
# ==

[[plugins]]
repo = 'chrisbra/Colorizer'

[[plugins]]
repo = 'sakshamgupta05/vim-todo-highlight'
hook_add  = '''
let g:todo_highlight_config = {
            \   'STEP': {
            \     'gui_fg_color': '#ffffff',
            \     'gui_bg_color': '#27AE60 ',
            \     'cterm_fg_color': 'white',
            \     'cterm_bg_color': 'green' },
            \   'NOTE': {
            \     'gui_fg_color': '#ffffff',
            \     'gui_bg_color': '#ffbd2a',
            \     'cterm_fg_color': 'white',
            \     'cterm_bg_color': '214'
            \   }
            \ }
'''

# ==
# == General Enhancement
# ==

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'tpope/vim-speeddating'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'mg979/vim-visual-multi'

[[plugins]]
repo = '907th/vim-auto-save'
hook_add  = '''
source $CONF_PATH/plug_conf/auto_save_conf.vim
'''

# ==
# == Fold
# ==

[[plugins]]
repo = 'lambdalisue/readablefold.vim'

# ==
# == Text object
# ==

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'thinca/vim-textobj-between'

# ==
# == Undo
# ==

[[plugins]]
repo = 'mbbill/undotree'

# ==
# == Async
# ==

[[plugins]]
repo = 'skywind3000/asyncrun.vim'

[[plugins]]
repo = 'skywind3000/asynctasks.vim'

# ==
# == Git
# ==

[[plugins]]
repo = 'rhysd/conflict-marker.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'APZelos/blamer.nvim'
